---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data

```{r loaddata}
library(data.table)
library(ggplot2)

dt_act<-data.table(read.csv("activity.csv"))

dt_totalsteps<-dt_act[,sum(steps,na.rm = TRUE),by=date]

names(dt_totalsteps)<-c("date","total_steps")


```

## What is mean total number of steps taken per day?

```{r}

data_summary<-summary(dt_totalsteps$total_steps)
print(data_summary)



```

## What is the average daily activity pattern?

```{r}
hist_totalsteps<-ggplot(data=dt_totalsteps,aes(total_steps))
hist_totalsteps<-hist_totalsteps+geom_histogram()+xlab("total steps")
print(hist_totalsteps)


dt_act[,step_mean:=mean(steps,na.rm=TRUE),by=interval]

g<-ggplot(data=dt_act,aes(interval,step_mean))
g<-g+geom_line()+ylab("Average steps")
print(g)
```


## Imputing missing values

```{r warning=FALSE, results="hide" }
dt_act[,old_steps:=steps]

dt_act[,steps:=replace(steps,is.na(steps),step_mean)]
```

## Are there differences in activity patterns between weekdays and weekends?
